# permissions for end users to view informixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: informix-viewer-role
rules:
- apiGroups:
  - actian.my.domain
  resources:
  - informixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - actian.my.domain
  resources:
  - informixes/status
  verbs:
  - get
