# permissions for end users to edit informixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: informix-editor-role
rules:
- apiGroups:
  - actian.my.domain
  resources:
  - informixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actian.my.domain
  resources:
  - informixes/status
  verbs:
  - get
